language: ruby
cache: bundler
script: bundle exec rake test
rvm:
 - 2.6
 - 2.4
 - 2.3
before_install:
  - gem update --system --no-document
  - gem install bundler --no-document
notifications:
  email:
    on_success: never
    on_failure: never
